export EXCON_DEBUG=1
export AZURE_TENANT_ID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
export AZURE_CLIENT_ID=YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY
export AZURE_CLIENT_SECRET=secret
export AZURE_SCOPE=api://ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ/.default
